In [1]:
import numpy as np
a1=np.array([[1,2,3],[4,5,6]])
print(a1,a1.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [2]:
np.arange(1,50)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [3]:
np.linspace(1,50,29)

array([ 1.  ,  2.75,  4.5 ,  6.25,  8.  ,  9.75, 11.5 , 13.25, 15.  ,
       16.75, 18.5 , 20.25, 22.  , 23.75, 25.5 , 27.25, 29.  , 30.75,
       32.5 , 34.25, 36.  , 37.75, 39.5 , 41.25, 43.  , 44.75, 46.5 ,
       48.25, 50.  ])

In [5]:
np.zeros((2,4),dtype=np.int32)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [6]:
np.ones((2,2),dtype=np.int32)

array([[1, 1],
       [1, 1]])

In [7]:
np.random.random((3,3))

array([[0.06414279, 0.62999527, 0.87084008],
       [0.54101503, 0.15775871, 0.09682105],
       [0.13436507, 0.31254744, 0.04932712]])

In [8]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.random.randn(3,4)

array([[ 0.28137181,  0.22045423,  1.00634757,  0.49934395],
       [ 0.82084935, -0.76600068, -0.66794118, -0.76340023],
       [-1.00834407,  0.5463997 , -0.61773512,  0.08693321]])

In [15]:
np.random.randint(1,100,(3,2))

array([[29, 18],
       [43, 89],
       [89, 63]])

In [16]:
a2=np.random.randint(1,100,(3,4))
print(a2)

[[54 90 58 38]
 [15  7 67 60]
 [72  2 38 99]]


In [17]:
a2[1:3,1:3]

array([[ 7, 67],
       [ 2, 38]])

In [21]:
np.max(a2, axis=1) # axis=1 rowwise and axis=0 columnwise

array([90, 67, 99])

In [23]:
np.min(a2,axis=1) # axis=1 rowwise and axis=0 columnwise

array([38,  7,  2])

In [25]:
a3=np.random.randint(1,57,10)
print(a3,np.argmax(a3))
print(a3,np.argmin(a3))

[52 56 29 18  7 28 38  3 45 22] 1
[52 56 29 18  7 28 38  3 45 22] 7


In [26]:
np.array([[1,1,1],[2,2,2]])+np.array([[3,3,3]])

array([[4, 4, 4],
       [5, 5, 5]])

In [27]:
np.add(np.array([[1,1,1],[2,2,2]]),np.array([[3,3,3]]))

array([[4, 4, 4],
       [5, 5, 5]])

In [28]:
np.array([[1,1,1],[2,2,2]])-np.array([[3,3,3]]) #np.subtract(a1,a2)

array([[-2, -2, -2],
       [-1, -1, -1]])

In [29]:
np.array([[1,1,1],[2,2,2]])*np.array([[3,3,3]])# np.multiply(a1,a2)

array([[3, 3, 3],
       [6, 6, 6]])

In [30]:
np.array([[1,1,1],[2,2,2]])/np.array([[3,3,3]])#np.divide(a1,a2)

array([[0.33333333, 0.33333333, 0.33333333],
       [0.66666667, 0.66666667, 0.66666667]])

In [31]:
a5=np.random.randint(1,600,(5,6))
print(a5)

[[179  65  33 283 326 350]
 [469 308  57 488 484 171]
 [306 186  61 327 461 261]
 [513 123 227 490 520 410]
 [147 165 580 139  76 470]]


In [36]:
a5[0:5:2,0:6:2]

array([[179,  33, 326],
       [306,  61, 461],
       [147, 580,  76]])

In [38]:
np.dot(np.array([[1,2,3],[1,2,3]]),np.array([[1],[3],[1]]))

array([[10],
       [10]])

In [41]:
np.mean(a2,axis=1)

array([60.  , 37.25, 52.75])

In [42]:
np.var(a2,axis=0)

array([ 566.        , 1628.66666667,  146.88888889,  636.22222222])

In [43]:
np.std(a2,axis=1)

array([18.86796226, 26.51768278, 36.40999176])

In [44]:
print(a2,a2.shape)

[[54 90 58 38]
 [15  7 67 60]
 [72  2 38 99]] (3, 4)


In [49]:
np.reshape(a2,(4,3))

array([[54, 90, 58],
       [38, 15,  7],
       [67, 60, 72],
       [ 2, 38, 99]])

In [50]:
np.resize(a2,(5,5))

array([[54, 90, 58, 38, 15],
       [ 7, 67, 60, 72,  2],
       [38, 99, 54, 90, 58],
       [38, 15,  7, 67, 60],
       [72,  2, 38, 99, 54]])

In [59]:
#Series
import pandas as pd
l=[1,2,3]
arr=np.array([10,20,30])
d={'a':1,'b':"hello",'c':3}

In [71]:
df1=pd.DataFrame(np.random.random((5,5)),index=['a','b','c','d','e'],
               columns=['p','q','r','s','t'])
df1

p         q         r         s         t
a  0.428336  0.710793  0.126856  0.817080  0.482452
b  0.008872  0.280510  0.757130  0.266038  0.903187
c  0.056305  0.551470  0.056024  0.340156  0.626754
d  0.016861  0.890947  0.874463  0.788550  0.550429
e  0.941108  0.190264  0.593913  0.549445  0.234686

In [70]:
df=pd.DataFrame({'Name':['x','y','z'],
                'roll_no':[1,2,3],
                'sub':['INT246']*3,
                'section':['KM025']*3})
df

Name  roll_no     sub section
0    x        1  INT246   KM025
1    y        2  INT246   KM025
2    z        3  INT246   KM025

In [72]:
df1

p         q         r         s         t
a  0.428336  0.710793  0.126856  0.817080  0.482452
b  0.008872  0.280510  0.757130  0.266038  0.903187
c  0.056305  0.551470  0.056024  0.340156  0.626754
d  0.016861  0.890947  0.874463  0.788550  0.550429
e  0.941108  0.190264  0.593913  0.549445  0.234686

In [75]:
df1['p'] # Accessing a single column

pandas.core.series.Series

In [76]:
df1[['p','s','r']] # Accessing multiple columns

p         s         r
a  0.428336  0.817080  0.126856
b  0.008872  0.266038  0.757130
c  0.056305  0.340156  0.056024
d  0.016861  0.788550  0.874463
e  0.941108  0.549445  0.593913

In [78]:
df1.loc[['a']]

p         q         r        s         t
a  0.428336  0.710793  0.126856  0.81708  0.482452

In [79]:
df1.loc[['a','c','d']] # Accessing Multiple rows

p         q         r         s         t
a  0.428336  0.710793  0.126856  0.817080  0.482452
c  0.056305  0.551470  0.056024  0.340156  0.626754
d  0.016861  0.890947  0.874463  0.788550  0.550429

In [80]:
df1.loc[['a','c'],['p','q']] # Accessing rows and colums

p         q
a  0.428336  0.710793
c  0.056305  0.551470

In [83]:
df.iloc[0:3,1:3]

roll_no     sub
0        1  INT246
1        2  INT246
2        3  INT246

In [85]:
df1.describe()

p         q         r         s         t
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean   0.290296  0.524797  0.481677  0.552254  0.559502
std    0.403525  0.291959  0.370753  0.251436  0.241954
min    0.008872  0.190264  0.056024  0.266038  0.234686
25%    0.016861  0.280510  0.126856  0.340156  0.482452
50%    0.056305  0.551470  0.593913  0.549445  0.550429
75%    0.428336  0.710793  0.757130  0.788550  0.626754
max    0.941108  0.890947  0.874463  0.817080  0.903187

In [86]:
df1

p         q         r         s         t
a  0.428336  0.710793  0.126856  0.817080  0.482452
b  0.008872  0.280510  0.757130  0.266038  0.903187
c  0.056305  0.551470  0.056024  0.340156  0.626754
d  0.016861  0.890947  0.874463  0.788550  0.550429
e  0.941108  0.190264  0.593913  0.549445  0.234686

In [88]:
df1[df1>0.6]

p         q         r        s         t
a       NaN  0.710793       NaN  0.81708       NaN
b       NaN       NaN  0.757130      NaN  0.903187
c       NaN       NaN       NaN      NaN  0.626754
d       NaN  0.890947  0.874463  0.78855       NaN
e  0.941108       NaN       NaN      NaN       NaN

In [93]:
df=pd.read_csv("C:\\Users\\hp\\Downloads\\iris (2).csv",header=None,
              names=['sepallength','sepalwidth','petallength','petalwidth','target'])
print(df)

     sepallength  sepalwidth  petallength  petalwidth          target
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]


In [91]:
df.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [95]:
df['sepallength'].describe()

count    150.000000
mean       5.843333
std        0.828066
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max        7.900000
Name: sepallength, dtype: float64

In [96]:
df1

p         q         r         s         t
a  0.428336  0.710793  0.126856  0.817080  0.482452
b  0.008872  0.280510  0.757130  0.266038  0.903187
c  0.056305  0.551470  0.056024  0.340156  0.626754
d  0.016861  0.890947  0.874463  0.788550  0.550429
e  0.941108  0.190264  0.593913  0.549445  0.234686

In [98]:
df1['f']=df1['p']+df1['r']

In [99]:
df1

p         q         r         s         t         f
a  0.428336  0.710793  0.126856  0.817080  0.482452  0.555192
b  0.008872  0.280510  0.757130  0.266038  0.903187  0.766002
c  0.056305  0.551470  0.056024  0.340156  0.626754  0.112329
d  0.016861  0.890947  0.874463  0.788550  0.550429  0.891325
e  0.941108  0.190264  0.593913  0.549445  0.234686  1.535021

In [102]:
df1.drop('f',axis=1, inplace=True)  #AXis=1 for column inplace=True changes permanent

In [103]:
df1

p         q         r         s         t
a  0.428336  0.710793  0.126856  0.817080  0.482452
b  0.008872  0.280510  0.757130  0.266038  0.903187
c  0.056305  0.551470  0.056024  0.340156  0.626754
d  0.016861  0.890947  0.874463  0.788550  0.550429
e  0.941108  0.190264  0.593913  0.549445  0.234686